'use client';
import {useState,useEffect} from 'react';
import {ArrowUpRight,ArrowRight,Heart,Search,SlidersHorizontal,Star,Clock,CalendarDays,Phone,Leaf,Check,Headphones,ShieldCheck,ChevronRight,Mic,MicOff,PhoneOff,Copy,Plus,Flower2,Sparkles,Menu,X} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Toaster,toast} from 'sonner';
const initialReaders=[
{id:1,name:'月乃 しずく',en:'SHIZUKU TSUKINO',letter:'月',color:'rose',skill:'タロット · 西洋占星術',topics:['恋愛','人間関係'],text:'言葉にならない想いにも、そっと寄り添います。',rate:180,rating:'4.98',reviews:128,status:'待機中',years:12},
{id:2,name:'花宮 すみれ',en:'SUMIRE HANAMIYA',letter:'花',color:'sage',skill:'四柱推命 · タロット',topics:['仕事','人生相談'],text:'あなたらしい選択を、一緒に見つけましょう。',rate:200,rating:'4.96',reviews:96,status:'待機中',years:10},
{id:3,name:'蒼井 凪',en:'NAGI AOI',letter:'凪',color:'blue',skill:'西洋占星術 · 数秘術',topics:['恋愛','仕事'],text:'心に静かな余白と、明日への小さな一歩を。',rate:160,rating:'4.95',reviews:84,status:'鑑定中',years:8},
{id:4,name:'小春',en:'KOHARU',letter:'春',color:'ochre',skill:'タロット · オラクルカード',topics:['人間関係','人生相談'],text:'どんなあなたも大丈夫。心が軽くなる時間を。',rate:150,rating:'4.97',reviews:112,status:'離席中',years:9}
];
type Reader=typeof initialReaders[number];
type Booking={id:number;name:string;date:string;time:string;duration:string;status:string;rate:number};
function Pick({value,onChange,items}:{value:string;onChange:(v:string)=>void;items:string[]}){return <Select value={value} onValueChange={onChange}><SelectTrigger className="picker"><SelectValue/></SelectTrigger><SelectContent>{items.map(i=><SelectItem key={i} value={i}>{i}</SelectItem>)}</SelectContent></Select>}
function Avatar({reader,large=false}:{reader:Reader;large?:boolean}){return <div className={'avatar '+reader.color+(large?' large':'')}><span>{reader.letter}</span><Flower2 size={large?28:19}/></div>}
export default function Home(){
const [view,setView]=useState('find'),[category,setCategory]=useState('すべて'),[query,setQuery]=useState(''),[available,setAvailable]=useState(false),[sort,setSort]=useState('おすすめ順'),[favorites,setFavorites]=useState<number[]>([]),[readers,setReaders]=useState(initialReaders),[selected,setSelected]=useState<Reader|null>(null),[mode,setMode]=useState('20分'),[date,setDate]=useState('2026-09-17'),[time,setTime]=useState('20:00'),[bookings,setBookings]=useState<Booking[]>([]),[call,setCall]=useState<Booking|null>(null),[seconds,setSeconds]=useState(0),[muted,setMuted]=useState(false),[info,setInfo]=useState(''),[review,setReview]=useState(false),[reviewText,setReviewText]=useState(''),[stars,setStars]=useState(5),[completed,setCompleted]=useState(2),[threshold,setThreshold]=useState('3'),[events,setEvents]=useState([{title:'秋の夜長、自分と向き合う時間。',date:'2026.09.12',tag:'特集'},{title:'新しい占い師が紬に加わりました。',date:'2026.09.10',tag:'お知らせ'}]),[eventTitle,setEventTitle]=useState(''),[readerName,setReaderName]=useState(''),[schedule,setSchedule]=useState<string[]>(['9月17日 19:00–23:00']),[mobile,setMobile]=useState(false);
useEffect(()=>{if(!call)return;const id=setInterval(()=>setSeconds(v=>v+1),1000);return()=>clearInterval(id)},[call]);
useEffect(()=>{if(call&&call.duration!=='従量制'&&seconds>=parseInt(call.duration)*60){endCall()}},[seconds,call]);
useEffect(()=>{const context=(document as any).modelContext;if(!context)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'start_reader_booking',description:'Open the demo reservation request form for a reader; does not submit a booking.',inputSchema:{type:'object',properties:{readerId:{type:'number'}},required:['readerId'],additionalProperties:false},execute:({readerId}:{readerId:number})=>{const reader=initialReaders.find(r=>r.id===readerId);if(!reader)throw new Error('Unknown reader');setSelected(reader);return {readerId,formOpened:true}}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort()},[]);
const navigate=(v:string)=>{setView(v);setMobile(false);window.scrollTo({top:0,behavior:'smooth'})};
const filtered=readers.filter(r=>(category==='すべて'||r.topics.includes(category))&&(!available||r.status==='待機中')&&(r.name+r.skill+r.topics.join('')).includes(query)&&(view!=='favorites'||favorites.includes(r.id))).sort((a,b)=>sort==='料金が安い順'?a.rate-b.rate:sort==='評価が高い順'?Number(b.rating)-Number(a.rating):a.id-b.id);
function submitBooking(e:React.FormEvent){e.preventDefault();if(!selected)return;const starts=new Date(date+'T'+time);if(starts.getTime()<Date.now()){toast.error('未来の日時を選択してください');return}setBookings(v=>[...v,{id:Date.now(),name:selected.name,date,time,duration:mode,status:'承認待ち',rate:selected.rate}]);setSelected(null);toast.success('予約リクエストを受け付けました');navigate('bookings')}
function endCall(){setCall(null);setCompleted(v=>v+1);toast.success('体験通話を終了しました（請求はありません）');if(completed+1>=Number(threshold))setReview(true)}
return <><Toaster position="bottom-center"/><header className="header"><button className="brand" onClick={()=>navigate('find')}><span className="brand-symbol">紬</span><span>tsumugi<small>心をほどく、電話占い</small></span></button><nav className={mobile?'open':''}>{[['find','占い師を探す'],['bookings','予約・鑑定履歴'],['favorites','お気に入り']].map(([v,l])=><button className={view===v?'active':''} key={v} onClick={()=>navigate(v)}>{l}</button>)}<button onClick={()=>setInfo('how')}>はじめての方へ <ArrowUpRight size={13}/></button></nav><button className={'account '+(view==='admin'?'active':'')} onClick={()=>navigate('admin')}>占い師・運営ページ <ArrowUpRight size={15}/></button><button className="mobile-toggle" aria-label="メニュー" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button></header>
<div className="demo-strip">体験版 <span>予約から鑑定までの流れをお試しいただけます。通話・決済はデモです。</span></div>
<main>
{(view==='find'||view==='favorites')&&<>
{view==='find'&&<section className="hero"><div className="hero-copy"><p className="eyebrow"><span/> A MOMENT FOR YOURSELF</p><h1>話すことで、<br/>ほどける心がある。</h1><p className="hero-description">ひとりで抱えなくて、大丈夫。<br/>あなたの想いに寄り添う占い師と、ここで。</p><a className="primary" href="#readers">心に合う占い師を見つける <ArrowRight size={17}/></a><div className="hero-note"><Headphones size={16}/> アプリ不要 <i/> 1分150円から <i/> 安心の事前料金表示</div></div><div className="hero-image"><img src="/hero.png" alt="木漏れ日の中に置かれた花とタロットカード"/><div className="image-label">少し、心に余白を。<span>YOUR TIME, YOUR PACE.</span></div></div></section>}
{view==='find'&&<div className="promise-row"><span><Headphones/>ブラウザで、気軽につながる</span><span><Clock/>20分から、自分のペースで</span><span><ShieldCheck/>承認後に確定する、安心の予約</span></div>}
<section className="reader-section" id="readers"><div className="section-heading"><div><p className="eyebrow">FIND YOUR GUIDE</p><h2>{view==='favorites'?'お気に入りの占い師':'あなたに寄り添う占い師'}</h2></div><span className="online-count"><b/> {readers.filter(r=>r.status==='待機中').length}名の占い師が待機中</span></div><div className="filter-row"><div className="categories">{['すべて','恋愛','仕事','人間関係','人生相談'].map((c,i)=><button key={c} className={category===c?'selected':''} onClick={()=>setCategory(c)}>{i===0?<Sparkles size={15}/>:i===1?<Heart size={15}/>:null}{c}</button>)}</div><label className="search"><Search size={17}/><input placeholder="占い師名・占術で検索" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="result-row"><span>{filtered.length}名の占い師 <small>料金はすべて税込</small></span><div><button className={'availability '+(available?'on':'')} onClick={()=>setAvailable(!available)}><span className="toggle"><i/></span>待機中のみ</button><Pick value={sort} onChange={setSort} items={['おすすめ順','料金が安い順','評価が高い順']}/></div></div>
<div className="reader-grid">{filtered.map(r=><article className="reader-card" key={r.id}><div className="card-top"><span className={'status '+(r.status==='待機中'?'online':r.status==='鑑定中'?'busy':'')}><i/>{r.status}</span><button aria-label={favorites.includes(r.id)?'お気に入りを解除':'お気に入りに追加'} className={'favorite '+(favorites.includes(r.id)?'saved':'')} onClick={()=>setFavorites(v=>v.includes(r.id)?v.filter(i=>i!==r.id):[...v,r.id])}><Heart size={19}/></button></div><Avatar reader={r} large/><div className="reader-identity"><h3>{r.name}<small>先生</small></h3><p>{r.en}</p></div><p className="skill">{r.skill}</p><div className="rating"><Star size={14} fill="currentColor"/><b>{r.rating}</b><span>（{r.reviews}件）</span><i/>鑑定歴{r.years}年</div><p className="reader-description">{r.text}</p><div className="tags">{r.topics.map(t=><span key={t}>{t}</span>)}</div><div className="card-bottom"><div><strong>{r.rate}</strong>円<span> / 分</span></div><button onClick={()=>setSelected(r)}>プロフィール・予約 <ArrowRight size={14}/></button></div></article>)}</div>{filtered.length===0&&<div className="empty"><Heart/><h3>{view==='favorites'?'気になる先生を、お気に入りに。':'条件に合う占い師が見つかりません'}</h3><p>{view==='favorites'?'先生のカードのハートを押すと、ここに表示されます。':'検索条件を変えて、もう一度お試しください。'}</p><button className="secondary" onClick={()=>{setCategory('すべて');setQuery('');setAvailable(false);navigate('find')}}>占い師一覧へ</button></div>}
</section>{view==='find'&&<section className="news"><div><p className="eyebrow">JOURNAL & NEWS</p><h2>紬からのお便り</h2></div><div>{events.map((n,i)=><button className="news-row" key={i} onClick={()=>setInfo(n.title)}><time>{n.date}</time><span>{n.tag}</span><b>{n.title}</b><ArrowUpRight size={17}/></button>)}</div></section>}
</>}
{view==='bookings'&&<section className="workspace"><p className="eyebrow">YOUR MOMENTS</p><h1>予約・鑑定履歴</h1><p className="subcopy">予約リクエストは、先生の承認後に確定します。</p>{!bookings.length?<div className="empty"><CalendarDays/><h3>まだ予約はありません</h3><p>気になる先生を見つけて、心をほどく時間を。</p><button className="primary" onClick={()=>navigate('find')}>占い師を探す <ArrowRight size={17}/></button></div>:bookings.map(b=><div className="booking-row" key={b.id}><div><span className="status">{b.status}</span><h3>{b.name} 先生</h3><p>{b.date}　{b.time} · {b.duration} · {b.rate}円 / 分</p></div>{b.status==='予約確定'?<button className="primary" onClick={()=>{setCall(b);setSeconds(0)}}><Phone size={16}/>通話を体験</button>:b.status==='承認待ち'?<button className="secondary" onClick={()=>setBookings(v=>v.map(x=>x.id===b.id?{...x,status:'キャンセル済み'}:x))}>キャンセル</button>:null}</div>)}<div className="soft-panel"><Star/><div><h3>先生へ、ありがとうを届けませんか？</h3><p>体験鑑定 {completed}回 · {threshold}回以上のリピートで口コミをご案内します。</p></div>{completed>=Number(threshold)&&<button className="secondary" onClick={()=>setReview(true)}>口コミを書く</button>}</div></section>}
{view==='admin'&&<section className="workspace"><div className="section-heading"><div><p className="eyebrow">PARTNER WORKSPACE</p><h1>占い師・運営ページ</h1></div><span className="demo-badge">デモ管理画面</span></div><div className="admin-grid"><div className="panel"><h3>現在のステータス</h3><div className="admin-reader"><Avatar reader={readers[0]}/><div><b>{readers[0].name} 先生</b><p>相談者に表示する状態を設定</p></div></div><Pick value={readers[0].status} onChange={s=>{setReaders(v=>v.map((r,i)=>i===0?{...r,status:s}:r));toast.success('ステータスを変更しました')}} items={['待機中','鑑定中','離席中','受付終了']}/></div><div className="panel"><h3>紹介プログラム</h3><p>あなたのSNSやブログから、相談者とつながる。</p><div className="metric">¥3,600 <small>紹介報酬のサンプル</small></div><button className="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(location.origin+'/?ref=shizuku');toast.success('紹介リンクをコピーしました')}catch{toast.error('コピーできませんでした')}}}><Copy size={15}/>紹介リンクをコピー</button><small className="hint">料率10%の表示例。成果計測・支払いは未接続です。</small></div></div>
<div className="panel"><h3>予約リクエスト <span className="count">{bookings.filter(b=>b.status==='承認待ち').length}</span></h3>{!bookings.filter(b=>b.status==='承認待ち').length?<p className="muted">新しい予約リクエストはありません。</p>:bookings.filter(b=>b.status==='承認待ち').map(b=><div className="request-row" key={b.id}><div><b>{b.name} 先生への予約</b><p>{b.date} {b.time} · {b.duration}</p></div><button className="secondary" onClick={()=>setBookings(v=>v.map(x=>x.id===b.id?{...x,status:'見送り'}:x))}>見送る</button><button className="primary" onClick={()=>{setBookings(v=>v.map(x=>x.id===b.id?{...x,status:'予約確定'}:x));toast.success('予約を承認しました')}}>承認する</button></div>)}</div>
<div className="admin-grid"><div className="panel"><h3><CalendarDays size={19}/>待機スケジュール</h3>{schedule.map((s,i)=><div className="schedule-row" key={s}>{s}<button aria-label="スケジュールを削除" onClick={()=>setSchedule(v=>v.filter((_,j)=>i!==j))}><X size={16}/></button></div>)}<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(String(f.get('end'))<=String(f.get('start'))){toast.error('終了時刻は開始時刻より後にしてください');return}setSchedule(v=>[...v,`${f.get('day')} ${f.get('start')}–${f.get('end')}`]);toast.success('スケジュールを追加しました')}}><div className="inline-inputs"><input aria-label="待機日" name="day" type="date" required/><input aria-label="開始時刻" name="start" type="time" defaultValue="19:00" required/><input aria-label="終了時刻" name="end" type="time" defaultValue="23:00" required/></div><button className="secondary"><Plus size={15}/>時間を追加</button></form></div><div className="panel"><h3><Star size={19}/>口コミのご案内</h3><p>同じ先生へのリピート回数に応じて、鑑定終了後に投稿フォームを表示します。</p><label>案内を表示する回数</label><Pick value={threshold} onChange={setThreshold} items={['3','5','10']}/><small className="hint">体験版では画面内で案内します。メール配信は未接続です。</small></div></div>
<div className="admin-grid"><div className="panel"><h3>お知らせを投稿</h3><form onSubmit={e=>{e.preventDefault();setEvents(v=>[{title:eventTitle,date:new Date().toLocaleDateString('ja-JP').replaceAll('/','.'),tag:'お知らせ'},...v]);setEventTitle('');toast.success('トップページに掲載しました')}}><label htmlFor="event">タイトル</label><input id="event" value={eventTitle} onChange={e=>setEventTitle(e.target.value)} placeholder="新しいお知らせ" required maxLength={80}/><button className="primary">掲載する <ArrowRight size={15}/></button></form></div><div className="panel"><h3>占い師を追加</h3><form onSubmit={e=>{e.preventDefault();setReaders(v=>[...v,{...initialReaders[3],id:Date.now(),name:readerName,letter:readerName[0],en:'NEW GUIDE',rating:'—',reviews:0,status:'受付終了',years:1}]);setReaderName('');toast.success('占い師を追加しました')}}><label htmlFor="reader">占い師名</label><input id="reader" value={readerName} onChange={e=>setReaderName(e.target.value)} placeholder="お名前" required maxLength={30}/><button className="secondary"><Plus size={15}/>追加する</button></form></div></div><p className="hint">この体験版の変更は、ページを再読み込みするとリセットされます。</p></section>}
</main><footer><button className="brand" onClick={()=>navigate('find')}><span className="brand-symbol">紬</span><span>tsumugi<small>あなたと、明日を紡ぐ。</small></span></button><p>© 2026 tsumugi <span>心に寄り添う、ひとときを。</span></p><button onClick={()=>setInfo('about')}>このサービスについて <ArrowUpRight size={14}/></button></footer>
<Dialog open={!!selected} onOpenChange={o=>!o&&setSelected(null)}><DialogContent className="booking-dialog"><DialogTitle>先生に、相談する</DialogTitle><DialogDescription>予約は先生の承認後に確定します。現在は体験版です。</DialogDescription>{selected&&<><div className="profile-head"><Avatar reader={selected}/><div><h2>{selected.name} 先生</h2><p>{selected.skill}</p></div></div><p>{selected.text}</p><form onSubmit={submitBooking}><label>鑑定プラン</label><Pick value={mode} onChange={setMode} items={['20分','30分','従量制']}/><div className="form-grid"><div><label htmlFor="date">希望日</label><input id="date" type="date" value={date} onChange={e=>setDate(e.target.value)} required/></div><div><label>希望時刻</label><Pick value={time} onChange={setTime} items={['10:00','11:00','14:00','15:00','18:00','19:00','20:00','21:00']}/></div></div><div className="price-summary"><span>{mode==='従量制'?'1分あたりの料金':'鑑定料金（税込）'}</span><b>¥{(selected.rate*(mode==='従量制'?1:parseInt(mode))).toLocaleString()}</b></div><p className="hint">{mode==='従量制'?'終了するまで1分単位で加算。次の予約に重ならないよう、先生が確認して承認します。':'指定時間で終了するプランです。'} 体験版では料金は発生しません。</p><button className="primary full">予約をリクエスト <ArrowRight size={16}/></button></form></>}</DialogContent></Dialog>
<Dialog open={!!call} onOpenChange={o=>!o&&endCall()}><DialogContent className="call-dialog"><DialogTitle>鑑定ルーム</DialogTitle><DialogDescription>通話画面のデモです。音声は送受信されません。</DialogDescription><div className="call-orb"><Headphones size={40}/></div><h2>{call?.name} 先生</h2><p>体験セッション</p><div className="timer">{Math.floor(seconds/60).toString().padStart(2,'0')}:{(seconds%60).toString().padStart(2,'0')}</div><p>概算 ¥{call?Math.ceil(seconds/60)*call.rate:0} · 請求なし</p><div className="call-controls"><button className="secondary" onClick={()=>setMuted(!muted)}>{muted?<MicOff/>:<Mic/>}{muted?'ミュート解除':'ミュート'}</button><button className="end-call" onClick={endCall}><PhoneOff/>終了する</button></div></DialogContent></Dialog>
<Dialog open={review} onOpenChange={setReview}><DialogContent><DialogTitle>あなたの声を、お聞かせください。</DialogTitle><DialogDescription>リピートしてくださり、ありがとうございます。</DialogDescription><form onSubmit={e=>{e.preventDefault();setReview(false);setReviewText('');toast.success('口コミを受け付けました（体験版）')}}><div className="stars">{[1,2,3,4,5].map(n=><button key={n} type="button" aria-label={`${n}つ星`} onClick={()=>setStars(n)}><Star fill={n<=stars?'currentColor':'none'}/></button>)}</div><textarea aria-label="口コミ" placeholder="鑑定を受けた感想をお書きください" value={reviewText} onChange={e=>setReviewText(e.target.value)} required/><button className="primary full">口コミを投稿</button></form></DialogContent></Dialog>
<Dialog open={!!info} onOpenChange={o=>!o&&setInfo('')}><DialogContent><DialogTitle>{info==='how'?'はじめての紬':info==='about'?'紬について':info}</DialogTitle><DialogDescription>{info==='how'?'あなたのペースで、相談を始めましょう。':'心をほどく、電話占い。'}</DialogDescription>{info==='how'?<div className="steps"><p><b>01　占い師を選ぶ</b><br/>得意な相談や占術から、気になる先生を探します。</p><p><b>02　予約をリクエスト</b><br/>20分・30分・従量制から選択。先生の承認をお待ちください。</p><p><b>03　ブラウザで相談</b><br/>予約履歴から鑑定ルームへ。体験版では音声通話・決済は行いません。</p></div>:<p className="article-copy">{info==='about'?'紬は、相談者と占い師が心地よく出会うためのサービスです。このサイトは操作をお試しいただく体験版です。掲載されている占い師・評価・報酬はサンプルであり、実際の予約、通話、決済、紹介成果の計測は行われません。':'季節の移ろいに合わせて、少しだけ立ち止まる時間を。日々の気がかりや、これからのこと。あなたの想いに寄り添う先生と、ゆっくりお話ししてみませんか。'}</p>}</DialogContent></Dialog>
</>}
